- name: adding host playbook
  hosts: 10.189.126.15
  tasks:
  - name: Add host to group 'just_created' with variable foo=42
    add_host:
      name: 10.189.126.15
      groups: ajeeb_aman_serv
      foo: 42
  - name: Add host to group 'just_created' with variable foo=44
    add_host:
      name: 10.189.126.14
      groups: ajeeb_aman_serv
      foo: 44
- name: Ping and List
  hosts: ajeeb_aman_serv
  tasks:
    - name: Hello Message
      ping:
    - name: list
      command: ls
      register: myoutput
    - set_fact:
        myoutput={{ myoutput.stdout }}
    - debug: var=myoutput
      run_once: true
