- name: Exec POST
  hosts: all
  user: ajeeb
  tasks:
    - name: post to fastlibvirt
      uri:
        url: http://10.189.126.14:8085/fastlibvirt/pausedomain
        method: POST
        body: "{{ lookup('file','/var/lib/awx/projects/domif.json') }}"
        body_format: json
        headers:
          Content-Type: "application/json"
