- name: Get Device Facts
  hosts: 172.28.12.137
  connection: local
  gather_facts: no

  tasks:
#     - name: Print version
#       junos_command:
#          command: show version
    - name: run commands and specify the output format
      junos_command:
        commands: show version
        display: json
#         commands:
#           - show version
#           - show interfaces
