# - name: Get Device Facts
#   hosts: 172.28.12.137
#   connection: local
#   gather_facts: no

#   tasks:
#     - name: Print version
#       junos_command:
#          command: show version
#     - name: run commands and specify the output format
#       junos_command:
#         commands: show version
#         display: json
#         commands:
#           - show version
#           - show interfaces


- name: Examples of juniper_junos_command
  hosts: 172.28.12.137
  connection: local
  gather_facts: no
#   roles:
#     - Juniper.junos

  tasks:
    - name: collect default set of facts
      junos_facts:
    - name: Execute single "show version" command.
      junos_command:
        commands: "show version"
      register: response

    - name: Print the command output
      debug:
        var: response.stdout

    - name: Execute single "show version" command.
      junos_command:
        commands: "show interfaces"
      register: response

    - name: Print the command output
      debug:
        var: response.stdout
        
    - name: Execute single "show version" command.
      junos_command:
        commands: "show interfaces terse ge-0/0/0"
      register: response

    - name: Print the command output
      debug:
        var: response.stdout
