- name: Ping and List
  hosts: all
  user: ajeeb
  tasks:
    - name: Hello Message
      ping:
    - name: list
      command: ls
      register: myoutput
    - set_fact:
        myoutput={{ myoutput.stdout }}
    - debug: var=myoutput
      run_once: true
