- name: Ping and List
  hosts: "{{ variable_host | default('all') }}"
  tasks:
    - name: Ping
      ping:
    - name: list
      command: ls
    - name: check storage CentOS
      command: "{{ free if ansible_facts['distribution'] == "CentOS" else swapinfo }}"
      register: linuxoutput
#    - debug: var=linuxoutput.stdout_lines
    - name: check storage FreeBSD
      command: free if ansible_facts['distribution'] == "CentOS" else swapinfo
      register: bsdoutput
    - name: DEBUG output for Linux servers 
      debug: var=linuxoutput.stdout_lines
      when: ansible_facts['distribution'] == "CentOS"
    - name: DEBUG output for BSD servers 
      debug: var=bsdoutput.stdout_lines 
      when: ansible_facts['distribution'] == "FreeBSD"
    #- debug: var=bsdoutput.stdout_lines if ansible_facts['distribution'] == "FreeBSD" else var=linuxoutput.stdout_lines
#tr_result: "{{ '{\"status\": \"SUCCESS\"}' if (op_result['output'] == 'Deleted') else '{\"status\" : \"FAILED\"}' }}"
