- name: Ping and List
  hosts: "{{ variable_host | default('all') }}"
  tasks:
    - name: Ping
      ping:
    - name: list
      command: ls
    - name: check Memory CentOS
      command: free
      when: ansible_facts['distribution'] == "CentOS"
      register: linuxoutput
    - name: check Memory FreeBSD
      command: swapinfo
      when: ansible_facts['distribution'] == "FreeBSD"
      register: bsdoutput
    - name: DEBUG output for Linux servers 
      debug: var=linuxoutput.stdout_lines
      when: ansible_facts['distribution'] == "CentOS"
    - name: DEBUG output for BSD servers 
      debug: var=bsdoutput.stdout_lines
      when: ansible_facts['distribution'] == "FreeBSD"
    - name: Juniper Commands
      junos_command:
        commands:
          - show version
          - show interfaces
      when: ansible_facts['distribution'] == "Juniper"
