- name: Ping and List
  hosts: "{{ variable_host | default('all') }}"
  tasks:
    - name: Ping
      ping:
    - name: list
      command: ls
    - name: check storage CentOS
      command: free
      when: ansible_facts['distribution'] == "CentOS"
      register: linuxoutput
    - name: check storage FreeBSD
      command: swapinfo
      when: ansible_facts['distribution'] == "FreeBSD"
      register: bsdoutput
    - name: Define bsd output
      set_fact:
         myoutput={{ bsdoutput.stdout_lines }}
      when: ansible_facts['distribution'] == "FreeBSD"
    - name: Define linux output
      set_fact:
        myoutput={{ linuxoutput.stdout_lines }}
      when: ansible_facts['distribution'] == "CentOS"
    - debug: var=myoutput
